// Static detail loader and index — generated by tools/data-pipeline/generate.ts
// Single source of truth for shard algorithm and shard count.
var loadDetail = require('../../detail-loaders')
var detailIndex = require('../../detail-index')

Page({
  data: {
    officer: null,
    portraitFail: false,
    activeSkills: [],
    passiveSkills: [],
  },

  onLoad: function (options) {
    var id = options.id
    if (!id) return

    // Lazy-load via generated index + static loaders
    var raw = loadDetail(id, detailIndex)
    if (!raw) return

    var recruitmentCityText = (raw.rc.cn && raw.rc.cn.length > 0)
      ? raw.rc.cn.join('、')
      : '無'

    // Build active/passive skill arrays directly from raw data
    // (avoid duplicating skills inside the officer object)
    var activeSkills = []
    var passiveSkills = []
    ;(raw.ss || []).forEach(function (s) {
      var skill = {
        skillId: s.si,
        kind: s.k,
        unlockLevel: s.ul,
        level: s.lv,
        name: s.n,
        iconPath: s.ip,
      }
      if (s.k === 'active') {
        activeSkills.push(skill)
      } else {
        passiveSkills.push(skill)
      }
    })

    var officer = {
      name: raw.n,
      rarityName: raw.rn,
      typeName: raw.tn,
      genderName: raw.gn,
      jobName: raw.jn,
      nationalityName: raw.nn,
      portraitPath: raw.pp,
      languages: (raw.ls || []).map(function (l) {
        return { languageId: l.li, level: l.lv, name: l.n }
      }),
      recruitment: {
        cityText: recruitmentCityText,
        requirementName: raw.rc.rn,
        note: raw.rc.nt,
      },
    }

    this.setData({
      officer: officer,
      activeSkills: activeSkills,
      passiveSkills: passiveSkills,
    })
    wx.setNavigationBarTitle({ title: officer.name })
  },

  onPortraitError: function () {
    this.setData({ portraitFail: true })
  },
})
